media_url: /web/
static_url: /static/
media_root: ../media/
db_root: ../db/
staticfiles_dirs:
  - ../static/
locale_paths:
  - ../locale/
template_dirs:
  - ../templates/
worlds:
  images_root: ../media/worlds/__attach/
  images_url: /web/worlds/__attach/
